


# test from 04-15-R02N1
db_id = 4334700.01
regions = [3]

# with 47.5%:
new_sequence1 = "GTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCAGTGGCGAAGGCGGCCTCCTGGACGAAGACTGACGCTCAGGTACGAAAGCGTGGGGAGCAAACA" \
                "GGATTAGATACCCTGGTAGTCCATGCTGTAAACGATGTCGATTCAGGATTAGATACCCTGGTAGTCCATGCTGTAAACGATGTCGATTTGAAGGTTGTAGCT" \
                "ATAAGCTGTAGCTTTCGGAGCTAATGCGTTAAATCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGG"

# with 22%
new_sequence2 = "GTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCAGTGGCGAAGGCGGCCTCCTGGACGAAGACTGACGCTCAGGTACGAAAGCGTGGGGAGCAAACA" \
                "GGATTAGATACCCTGGTAGTCCATGCTGTAAACGATGTCGATTCAGGATTAGATACCCTGGTAGTCCATGCTGTAAACGATGTCGATTTGAAGGTTGTAGCT" \
                "ATAAGCTGTAGCTTTCGGAGCTAATGCGTTAAATCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAAGGAATTGACGGG"

new_seq3 = "GTGTAGCGGTGGAATGCGTAGAGATCTGGAGGAATACCAGTGGCGAAGGCGGCCTCCTGGACGAAGACTGACGCTCAGGTACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCATGCTGTAAACGATGTCGATTCAGGATTAGATACCCTGGTAGTCCATGCTGTAAACGATGTCGATTTGAAGGTTGTAGCTATAAGCTGTAGCTTTCGGAGCTAATGCGTTAAATCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGG"


db_seq = "GTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCAGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTACGAAAGCGTGGGGAGCAAACAGGATTAG" \
         "ATACCCTGGTAGTCCATGCTGTAAACGATGTCGATTTGAAGGTTGTGGCCTAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCATGCTGTAAACGATGTCGA" \
         "TTTGAAGGTTGTGGCCTTGAGCTGTGGCTTTCGAAGCTAACGCGTTAAATCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGG"


def dist_from_db(new_seq, db_seq):
    counter=0
    for i in range(len(new_seq)/2):
        counter += (new_seq[i] != db_seq[i]) + (new_seq[-i] != db_seq[-i])
    print counter

dist_from_db(new_sequence1, db_seq)
dist_from_db(new_sequence2, db_seq)
dist_from_db(new_seq3, new_sequence1)

print "".join(new_sequence1[:len(new_sequence1)/2])
# grep <sequence> 04-15-R02N1_S34_L001_R1_001.fastq | wc -l
print "".join(new_sequence2[:len(new_sequence2)/2])
print "".join(new_seq3[:len(new_sequence2)/2])

print "\nBW:"
# print reverse and complete
cdict = {'A': 'T', 'T': 'A', 'G':'C', 'C': 'G'}
print "".join([cdict[c] for c in new_sequence1[-145:][::-1]])
print "".join([cdict[c] for c in new_sequence2[-145:][::-1]])
print "".join([cdict[c] for c in new_seq3[-145:][::-1]])


# grep seq1 fw: 38210, bw: 28903
# grep seq2 fw: 38210, bw: 13688
# grep seq3 fw: 9473, bw: 28903
